// SPDX-License-Identifier: AGPL-3.0-or-later
import adminEndpoint from "@/hono/api/admin";
import appEndpoint from "@/hono/api/app";
import bookmarksEndpoint from "@/hono/api/bookmarks";
import calendarEndpoint from "@/hono/api/calendar";
import chatEndpoint from "@/hono/api/chat";
import commentsEndpoint from "@/hono/api/comments";
import healthEndpoint from "@/hono/api/health";
import imagesEndpoint from "@/hono/api/images";
import logoutEndpoint from "@/hono/api/logout";
import pinnedPostsEndpoint from "@/hono/api/pinned-posts";
import reactionsEndpoint from "@/hono/api/post-reactions";
import postsEndpoint, { publicPostsEndpoint } from "@/hono/api/posts";
import pushEndpoint from "@/hono/api/push";
import setupEndpoint from "@/hono/api/setup";
import shareEndpoint from "@/hono/api/share";
import videoEndpoint from "@/hono/api/video";
import videoAppEndpoint from "@/hono/api/video-app";
import { createHono } from "./factory";

export const apiHono = createHono().basePath("/api");

apiHono.route("/health", healthEndpoint);
apiHono.route("/setup", setupEndpoint);
apiHono.route("/share", shareEndpoint);
apiHono.route("/auth/logout", logoutEndpoint);
apiHono.route("/app/images", imagesEndpoint);
apiHono.route("/app/posts", postsEndpoint);
apiHono.route("/app/posts", commentsEndpoint);
apiHono.route("/app/posts", reactionsEndpoint);
apiHono.route("/app/posts", pinnedPostsEndpoint);
apiHono.route("/app/bookmarks", bookmarksEndpoint);
apiHono.route("/chat", chatEndpoint);
apiHono.route("/app/videos", videoAppEndpoint);
apiHono.route("/app/push", pushEndpoint);
apiHono.route("/app", appEndpoint);
apiHono.route("/admin", adminEndpoint);
apiHono.route("/admin/calendar", calendarEndpoint);
apiHono.route("/video", videoEndpoint);
apiHono.route("/public/posts", publicPostsEndpoint);
