/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as SharedPostIdRouteImport } from './routes/shared-post.$id'
import { Route as AuthErrorRouteImport } from './routes/auth/error'
import { Route as AppVideoRouteImport } from './routes/app/video'
import { Route as AppStatsRouteImport } from './routes/app/stats'
import { Route as AppNewVideoRouteImport } from './routes/app/new-video'
import { Route as AppNewRouteImport } from './routes/app/new'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppVideoIdRouteImport } from './routes/app/video.$id'
import { Route as AppPostIdRouteImport } from './routes/app/post.$id'
import { Route as AppPostIdEditRouteImport } from './routes/app/post.$id_.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SharedPostIdRoute = SharedPostIdRouteImport.update({
  id: '/shared-post/$id',
  path: '/shared-post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorRoute = AuthErrorRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVideoRoute = AppVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppNewVideoRoute = AppNewVideoRouteImport.update({
  id: '/new-video',
  path: '/new-video',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppVideoIdRoute = AppVideoIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppVideoRoute,
} as any)
const AppPostIdRoute = AppPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPostIdEditRoute = AppPostIdEditRouteImport.update({
  id: '/post/$id_/edit',
  path: '/post/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/new': typeof AppNewRoute
  '/app/new-video': typeof AppNewVideoRoute
  '/app/stats': typeof AppStatsRoute
  '/app/video': typeof AppVideoRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/shared-post/$id': typeof SharedPostIdRoute
  '/app/': typeof AppIndexRoute
  '/app/post/$id': typeof AppPostIdRoute
  '/app/video/$id': typeof AppVideoIdRoute
  '/app/post/$id/edit': typeof AppPostIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/new': typeof AppNewRoute
  '/app/new-video': typeof AppNewVideoRoute
  '/app/stats': typeof AppStatsRoute
  '/app/video': typeof AppVideoRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/shared-post/$id': typeof SharedPostIdRoute
  '/app': typeof AppIndexRoute
  '/app/post/$id': typeof AppPostIdRoute
  '/app/video/$id': typeof AppVideoIdRoute
  '/app/post/$id/edit': typeof AppPostIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/setup': typeof SetupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/new': typeof AppNewRoute
  '/app/new-video': typeof AppNewVideoRoute
  '/app/stats': typeof AppStatsRoute
  '/app/video': typeof AppVideoRouteWithChildren
  '/auth/error': typeof AuthErrorRoute
  '/shared-post/$id': typeof SharedPostIdRoute
  '/app/': typeof AppIndexRoute
  '/app/post/$id': typeof AppPostIdRoute
  '/app/video/$id': typeof AppVideoIdRoute
  '/app/post/$id_/edit': typeof AppPostIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/setup'
    | '/app/admin'
    | '/app/calendar'
    | '/app/new'
    | '/app/new-video'
    | '/app/stats'
    | '/app/video'
    | '/auth/error'
    | '/shared-post/$id'
    | '/app/'
    | '/app/post/$id'
    | '/app/video/$id'
    | '/app/post/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/app/admin'
    | '/app/calendar'
    | '/app/new'
    | '/app/new-video'
    | '/app/stats'
    | '/app/video'
    | '/auth/error'
    | '/shared-post/$id'
    | '/app'
    | '/app/post/$id'
    | '/app/video/$id'
    | '/app/post/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/setup'
    | '/app/admin'
    | '/app/calendar'
    | '/app/new'
    | '/app/new-video'
    | '/app/stats'
    | '/app/video'
    | '/auth/error'
    | '/shared-post/$id'
    | '/app/'
    | '/app/post/$id'
    | '/app/video/$id'
    | '/app/post/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SetupRoute: typeof SetupRoute
  AuthErrorRoute: typeof AuthErrorRoute
  SharedPostIdRoute: typeof SharedPostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/shared-post/$id': {
      id: '/shared-post/$id'
      path: '/shared-post/$id'
      fullPath: '/shared-post/$id'
      preLoaderRoute: typeof SharedPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/video': {
      id: '/app/video'
      path: '/video'
      fullPath: '/app/video'
      preLoaderRoute: typeof AppVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new-video': {
      id: '/app/new-video'
      path: '/new-video'
      fullPath: '/app/new-video'
      preLoaderRoute: typeof AppNewVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/video/$id': {
      id: '/app/video/$id'
      path: '/$id'
      fullPath: '/app/video/$id'
      preLoaderRoute: typeof AppVideoIdRouteImport
      parentRoute: typeof AppVideoRoute
    }
    '/app/post/$id': {
      id: '/app/post/$id'
      path: '/post/$id'
      fullPath: '/app/post/$id'
      preLoaderRoute: typeof AppPostIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/post/$id_/edit': {
      id: '/app/post/$id_/edit'
      path: '/post/$id/edit'
      fullPath: '/app/post/$id/edit'
      preLoaderRoute: typeof AppPostIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppVideoRouteChildren {
  AppVideoIdRoute: typeof AppVideoIdRoute
}

const AppVideoRouteChildren: AppVideoRouteChildren = {
  AppVideoIdRoute: AppVideoIdRoute,
}

const AppVideoRouteWithChildren = AppVideoRoute._addFileChildren(
  AppVideoRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppNewRoute: typeof AppNewRoute
  AppNewVideoRoute: typeof AppNewVideoRoute
  AppStatsRoute: typeof AppStatsRoute
  AppVideoRoute: typeof AppVideoRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPostIdRoute: typeof AppPostIdRoute
  AppPostIdEditRoute: typeof AppPostIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppNewRoute: AppNewRoute,
  AppNewVideoRoute: AppNewVideoRoute,
  AppStatsRoute: AppStatsRoute,
  AppVideoRoute: AppVideoRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPostIdRoute: AppPostIdRoute,
  AppPostIdEditRoute: AppPostIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SetupRoute: SetupRoute,
  AuthErrorRoute: AuthErrorRoute,
  SharedPostIdRoute: SharedPostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
